### PR TITLE
Drop optional dependencies

### PR DESCRIPTION
**Pull request by caspervdw**
Currently, scikit-image and pillow are listed as dependencies (check `conda info pims`). While the idea of pims is that it is as slim as possible.

So I am in favour of dropping these, so that the users can decide for themselves whether they want to pillow, scikit-image, or scipy.

Please wait for merge until @tacaswell @danielballan @ericdill @nkeim replied

### CODE REVIEW

**Comment by nkeim** [comment]
Agree. Note however that the [installation instructions](http://soft-matter.github.io/pims/v0.3.3/install.html) don't mention that Pillow is also needed for IPython display, only for tiff enhancements.

**Comment by ericdill** [comment]
> So I am in favour of dropping these, so that the users can decide for themselves whether they want to pillow, scikit-image, or scipy.

I would strongly prefer to include at least one of scipy/matplotlib/skimage.  `conda` does not have the notion of optional dependencies and if we don't ship one of those three libraries, ImageSequence isn't functional. I am currently trying to help some grad students learn image analysis in python and `pims` is a great library for that.  I (selfishly!) don't want to have to have any additional steps between `conda install pims` and `ImageSequence` being usable. I know that I will _always_ forget to include one of skimage/matplotlib/scipy in my `conda install pims` command for my own work and I do not want the cognitive overhead of having to remember to `conda install pims scipy`.  

With that being said, I am not trying to put my foot down or anything like that.  What do you see is the advantage of not including at least one of each of the optional dependencies?

**Comment by danielballan** [comment]
Another option: in lieu of optional dependencies, distribute two packages: pims and pims-core or pims and pims-extras.

**Comment by nkeim** [comment]
I like that idea... the superset should be called "pims". Packages like trackpy should prefer pims but also accept pims-core. Then if you know what you are doing, you can install pims-core explicitly before installing trackpy, and everything will work as expected. Otherwise you get batteries included.

On Oct 3, 2016, at 6:43 AM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:

Another option: in lieu of optional dependencies, distribute two packages: pims and pims-core or pims and pims-extras.

##

**Comment by ericdill** [comment]
Works for me too. Good idea @danielballan

**Comment by danielballan** [comment]
> Packages like trackpy should prefer pims but accept pims-core

Here we have the problem of optional dependencies over again: there is no way to express "prefer package X but accept Y" in a recipe.

However, we could likewise ship trackpy and trackpy-core, which actually sounds like a good idea to me since teackpy has accumulated optional deps like pytables.

The approach obviously does not scale well but I think it would get the job done here, while we wait for optional dependencies.

**Comment by caspervdw** [comment]
I am not sure about this approach. Given that conda allows multiple package versions, multiple versions of distributions seems to be potentially obscure to users and also more work to maintain. Apart from that,  the "core" version is on Pypi anyway, which always works as it is pure python.

I see the point of user-friendly conda packaging, including skimage and pillow by default. If somebody does not want them, we always have the `--no-deps` option.

So I prefer only one conda package with a "commonly used set" which could be skimage, pillow, jpype, imageio, and pyav/ffmpeg (when available).

Unexperienced users then have a decent starting set of packages. Core users should then use pypi or --no-deps (which should be documented).

**Comment by tacaswell** [comment]
I don't think we should document / suggest using `--no-deps`.  This will lead to people doing things like `conda create -n broken matplotlib pims --no-deps` which will end up missing numpy.

**Comment by caspervdw** [comment]
That is a valid point @tacaswell. For a minimal installation, we would need to advise `conda install numpy six slicerator` and then either `conda install pims --no-deps` or `pip install pims`.

Anyway, it seems that we all agree on leaving the conda `pims` distribution with some optional dependencies. How `pims-core` is implemented remains an open issue still.

For the scope of this PR, I suggest we replace `scikit-image` with `scipy` and keep `pillow`. This will pull in `libtiff` as well (dependency of `pillow`). So we could add that dependency too as pims makes use of it.

**Comment by tacaswell** [comment]
I think we should prefer `tifffile` over `libtiff`.  `tifffile` has much better support of weird bit-depth tiffs.

**Comment by caspervdw** [comment]
`libtiff` will be there anyway because of `pillow`. But I am :+1: of adding `tifffile` too.

**Comment by caspervdw** [comment]
To round up this optional dependency question, shall we do the following: pillow, jinja2, scipy, libtiff, tifffile?

**Review by tacaswell — APPROVED** [review]
I am :+1: on making the conda-package 'heavy'

**Comment by caspervdw** [comment]
Ok, libtiff at conda-forge is not the same as libtiff at PyPi. So I will drop that one after all, tiff support will be there through tifffile.

Possibly, ffmpeg and av (both working on conda-forge) could be included too, in order to support out of the box video reading.

**Comment by caspervdw** [comment]
To finalize this, the feedstock has to be regenerated after https://github.com/conda-forge/slicerator-feedstock/pull/4 is merged and distributed.

**Comment by danielballan** [comment]
I think I'm in favor of adding PyAV and friends as does eventually, but not in this pass. Want to see if we get any bugs reports on those for awhile before we make them a requirement.

**Pull request merged**
