### PR TITLE
Release 0.4.1

### PR DESCRIPTION
**Pull request by jakirkham**
```
This is a hotfix release to adjust to a change in our dependency, six, that made the library un-importable in Python 2. There are no other changes.
```

cc @danielballan

### CODE REVIEW

**Comment by jakirkham** [comment]
We could probably do a [`noarch: python`]( https://conda-forge.org/docs/meta.html#building-noarch-packages ) package, but felt like this was enough changes.

**Comment by jakirkham** [comment]
This is now passing. Please let me know if there is anything else. :)

**Comment by danielballan** [comment]
Thanks!

**Comment by jakirkham** [comment]
np.

Did the noarch Python part in PR ( https://github.com/conda-forge/pims-feedstock/pull/6 ). Please let me know if that is something you would be ok with.

**Pull request merged**
