### PR TITLE
MNT: Refresh feedstock

### LINKED ISSUE #11: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #11.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #11

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
cc @nkeim

**Comment by nkeim** [comment]
Thanks @jakirkham ! I would like to help but I am not a maintainer or contributor here. Could you, @tacaswell, or @danielballan please address that?

**Comment by nkeim** [comment]
`pip` must be included in the build requirements in `meta.yaml`

**Comment by jakirkham** [comment]
Thanks Nathan! Missed that. Should be fixed now. Also switched from `build` to `host`.

**Pull request merged**
