### PR TITLE
Use noarch Python

### PR DESCRIPTION
**Pull request by jakirkham**
As this is pure Python, OS agnostic, Python 2/3 compatible, and makes no use of selectors in the recipe, this is a good candidate for a noarch Python build. This confers with it less overhead and maintenance burden. Also allows for faster releases as it only builds once on CircleCI only to create packages.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please let me know your thoughts on this change.

**Comment by danielballan** [comment]
This is fine with me. I would like to hear input from @caspervdw and @ericdill before this gets merged.

**Comment by caspervdw** [comment]
Also fine with me!

**Comment by ericdill** [comment]
[Unless you are using ``constructor`` to deploy environments that include pims](https://github.com/conda/constructor/issues/86) I see no issue with noarch: python here.

**Comment by danielballan** [comment]
Great, thanks for flagging that Eric. I'm not _aware_ of anyone doing that...if they are I hope they will show up here to complain about it when we break them. Anyway, it looks like constructor will eventually support noarch packages.

**Comment by jakirkham** [comment]
Thanks everyone. :)

**Pull request merged**
